# 📋 Data Understanding — Used Car Price Prediction & Valuation System

This notebook provides a **basic data understanding** of the used car dataset.  
We cover the following:

| # | Section | Purpose |
|---|---------|----------|
| 1 | Dataset Overview | Shape, size, first/last rows |
| 2 | Data Fields Understanding | Column names, data types, brief descriptions |
| 3 | Missing Values Analysis | Count & percentage of nulls per column |
| 4 | Duplicate Data Check | Identify and quantify duplicate rows |
| 5 | Basic Statistical Summary | Descriptive statistics for numerical & categorical columns |
| 6 | Numerical vs Categorical Columns | Classify every column into its data type category |

> **Note:** This is a preliminary data inspection — no heavy analytics or EDA is performed here.

---
## 0. Imports & Data Loading

In [4]:
import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 60)
pd.set_option('display.float_format', '{:.2f}'.format)

In [5]:
# Resolve CSV path relative to this notebook's directory
NOTEBOOK_DIR = os.path.dirname(os.path.abspath('data_understanding.ipynb'))
CSV_PATH = os.path.join(NOTEBOOK_DIR, 'cars_data_clean.csv')

# Fallback to absolute path if the above doesn't find the file
if not os.path.exists(CSV_PATH):
    CSV_PATH = r'd:\MLPs\Used Car Price Prediction & Valuation System\cars_data_clean.csv'

# Load dataset
df = pd.read_csv(CSV_PATH)
print(f"✅ Dataset loaded successfully!")
print(f"   Source: {CSV_PATH}")

✅ Dataset loaded successfully!
   Source: d:\MLPs\Used Car Price Prediction & Valuation System\cars_data_clean.csv

---
## 1. Dataset Overview

In [6]:
print("="*60)
print("📊 DATASET OVERVIEW")
print("="*60)
print(f"Number of Rows    : {df.shape[0]:,}")
print(f"Number of Columns : {df.shape[1]}")
print(f"Total Data Points : {df.size:,}")
print(f"Memory Usage      : {df.memory_usage(deep=True).sum() / (1024**2):.2f} MB")
print("="*60)

============================================================
📊 DATASET OVERVIEW
============================================================
Number of Rows    : 37,813
Number of Columns : 66
Total Data Points : 2,495,658
Memory Usage      : 131.35 MB
============================================================

In [7]:
# First 5 rows
print("\n🔍 First 5 Rows:")
df.head()

🔍 First 5 Rows:

,usedCarSkuId,loc,myear,body,transmission,fuel,km,ip,images,imgCount,threesixty,dvn,oem,model,variant,City,listed_price,discountValue,utype,carType,top_features,comfort_features,interior_features,exterior_features,safety_features,Color,Engine Type,No of Cylinder,Valves per Cylinder,Valve Configuration,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seats,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,Doors,Cargo Volume,model_type_new,state,exterior_color,owner_type,Fuel Suppy System,Compression Ratio,Alloy Wheel Size,Ground Clearance Unladen,Max Power Delivered,Max Power At,Max Torque Delivered,Max Torque At,Bore,Stroke
0,7111bf25-97af-47f9-867b-40879190d800,gomti nagar,2016,hatchback,manual,cng,69162.00,0,[{'img': 'https://images10.gaadi.com/usedcar_image/origi...,15,False,maruti wagon r lxi cng,maruti,maruti wagon r,lxi cng,lucknow,370000.00,0,dealer,corporate,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'remote trunk ...","['air conditioner', 'heater', 'digital odometer', 'elect...","['adjustable head lights', 'manually adjustable exterior...","['centeral locking', 'child safety locks', 'day night re...",silver,k10b engine,3.00,4.00,dohc,False,False,3599.00,1495.00,1700.00,2400.00,1295.00,1290.00,960.00,1350.00,5 speed,fwd,5.00,power,4.60,ventilated disc,drum,137.00,15.90,tubeless,5.00,180.00,used,uttar pradesh,silver,first,NaN,NaN,NaN,NaN,58.16,6200.00,77.00,3500.00,69.00,NaN
1,c309efc1-efaf-4f82-81ad-dcb38eb36665,borivali west,2015,hatchback,manual,cng,45864.00,0,[{'img': 'https://images10.gaadi.com/usedcar_image/origi...,15,False,maruti celerio green vxi,maruti,maruti celerio,green vxi,mumbai,365000.00,0,dealer,corporate,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'power windows...","['air conditioner', 'heater', 'digital odometer', 'elect...","['adjustable head lights', 'manually adjustable exterior...","['centeral locking', 'child safety locks', 'day night re...",grey,k10b engine,3.00,4.00,dohc,False,False,3600.00,1600.00,1560.00,2425.00,1420.00,1410.00,915.00,1350.00,5 speed,fwd,5.00,power,4.70,ventilated disc,drum,150.00,15.05,tubeless radial,5.00,235.00,used,maharashtra,grey,first,Gasoline Port Injection,11.00,NaN,NaN,58.20,6000.00,78.00,3500.00,73.00,NaN
2,7609f710-0c97-4f00-9a47-9b9284b62d3a,jasola,2015,sedan,manual,cng,81506.00,0,[{'img': 'https://images10.gaadi.com/usedcar_image/origi...,15,False,honda amaze s plus i-vtec,honda,honda amaze,s plus i-vtec,new delhi,421000.00,0,dealer,corporate,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'power windows...","['air conditioner', 'heater', 'adjustable steering', 'di...","['adjustable head lights', 'power adjustable exterior re...","['centeral locking', 'power door locks', 'child safety l...",silver,i-vtec petrol engine,4.00,4.00,sohc,False,False,3990.00,1680.00,1505.00,2405.00,NaN,NaN,950.00,NaN,5 speed,fwd,5.00,power,4.50,disc,drum,160.00,15.00,tubeless radial,4.00,400.00,used,delhi,silver,second,NaN,NaN,NaN,NaN,86.70,6000.00,109.00,4500.00,NaN,NaN
3,278b76e3-5539-4a5e-ae3e-353a2e3b6d7d,jasola,2013,hatchback,manual,cng,115893.00,0,[{'img': ''}],0,False,maruti wagon r lxi cng,maruti,maruti wagon r,lxi cng,new delhi,240000.00,0,dealer,corporate,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'low fuel warn...","['air conditioner', 'heater', 'electronic multi tripmete...","['adjustable head lights', 'manually adjustable exterior...","['centeral locking', 'child safety locks', 'day night re...",silver,k series petrol engine,3.00,4.00,NaN,False,False,3595.00,1475.00,1700.00,2400.00,1295.00,1290.00,960.00,1350.00,5 speed,fwd,5.00,power,4.60,ventilated disc,drum,NaN,NaN,tubeless radial,4.00,NaN,used,delhi,silver,second,Multi-Point Fuel Injection,NaN,13.00,NaN,58.20,6200.00,77.00,3500.00,NaN,NaN
4,b1eab99b-a606-48dd-a75b-57feb8a9ad92,mumbai g.p.o.,2022,muv,manual,cng,18900.00,0,[{'img': 'https://images10.gaadi.com/usedcar_image/origi...,6,False,maruti ertiga vxi cng,maruti,maruti ertiga,vxi cng,mumbai,1175000.00,0,dealer,partner,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'power windows...","['air conditioner', 'heater', 'adjustable steering', 'ta...","['adjustable head lights', 'power adjustable exterior re...","['anti lock braking system', 'brake assist', 'centeral l...",white,k15c,4.00,4.00,NaN,True,True,4395.00,1735.00,1690.00,2740.00,NaN,NaN,1250.00,1820.00,5 speed,2wd,7.00,NaN,5.20,disc,drum,NaN,NaN,tubeless radial,5.00,NaN,used,maharashtra,white,first,NaN,12.00,NaN,NaN,86.63,5500.00,121.50,4200.00,NaN,NaN

In [8]:
# Last 5 rows
print("\n🔍 Last 5 Rows:")
df.tail()

🔍 Last 5 Rows:

,usedCarSkuId,loc,myear,body,transmission,fuel,km,ip,images,imgCount,threesixty,dvn,oem,model,variant,City,listed_price,discountValue,utype,carType,top_features,comfort_features,interior_features,exterior_features,safety_features,Color,Engine Type,No of Cylinder,Valves per Cylinder,Valve Configuration,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seats,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,Doors,Cargo Volume,model_type_new,state,exterior_color,owner_type,Fuel Suppy System,Compression Ratio,Alloy Wheel Size,Ground Clearance Unladen,Max Power Delivered,Max Power At,Max Torque Delivered,Max Torque At,Bore,Stroke
37808,ee6ce523-2aa6-4852-96a1-86b9bc277377,thathawade,2018,suv,manual,diesel,49882.00,0,[{'img': 'https://images10.gaadi.com/usedcar_image/origi...,15,False,tata nexon 1.5 revotorq xz plus,tata,tata nexon,1.5 revotorq xz plus,pune,881000.00,0,dealer,corporate,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'power windows...","['air conditioner', 'heater', 'adjustable steering', 'di...","['adjustable head lights', 'fog lights front', 'power ad...","['anti lock braking system', 'centeral locking', 'power ...",blue,"revotorq, 1.5l turbocharged engine",4.00,4.00,dohc,True,True,3994.00,1811.00,1607.00,2498.00,1540.00,1530.00,1305.00,NaN,6 speed,fwd,5.00,power,5.10,disc,drum,154.19,13.25,tubeless radial,5.00,350.00,used,maharashtra,blue,second,Common Rail Injection,NaN,16.00,209.00,108.50,3750.00,260.00,2125.00,76.00,82.50
37809,ba1994ac-53ab-4baf-913e-b72f01a37b5d,kharadi,2011,sedan,manual,diesel,82843.00,0,[{'img': 'https://images10.gaadi.com/usedcar_image/origi...,27,False,tata manza aura quadrajet bs iv,tata,tata manza,aura quadrajet bs iv,pune,245000.00,0,dealer,partner,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'power windows...","['air conditioner', 'heater', 'adjustable steering', 'ta...","['adjustable head lights', 'fog lights front', 'fog ligh...","['centeral locking', 'power door locks', 'child safety l...",white,"4 cylinder, common rail,",4.00,4.00,NaN,False,False,4413.00,1703.00,1550.00,2520.00,NaN,NaN,1200.00,1650.00,5 speed,fwd,5.00,power,5.10,ventilated disc,drum,NaN,NaN,tubeless radial,4.00,460.00,used,maharashtra,white,first,Common Rail Injection,NaN,15.00,NaN,88.80,4000.00,200.00,2375.00,NaN,NaN
37810,8f4448ae-53f5-4a3f-b13d-2401dd60c624,kothrud,2020,hatchback,manual,diesel,58000.00,0,[{'img': 'https://images10.gaadi.com/usedcar_image/origi...,11,False,tata altroz xz diesel,tata,tata altroz,xz diesel,pune,735000.00,0,dealer,partner,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'power windows...","['air conditioner', 'heater', 'adjustable steering', 'di...","['adjustable head lights', 'fog lights front', 'power ad...","['anti lock braking system', 'centeral locking', 'power ...",grey,1.5 l turbocharged revotorq,4.00,4.00,NaN,True,True,3990.00,1755.00,1523.00,2501.00,NaN,NaN,NaN,NaN,5 speed,NaN,5.00,power,5.00,disc,drum,NaN,NaN,tubeless radial,5.00,345.00,used,maharashtra,grey,first,NaN,NaN,16.00,NaN,88.77,4000.00,200.00,2125.00,NaN,NaN
37811,dbf9b629-7215-494b-a62d-ba1408531362,kothrud,2014,hatchback,manual,diesel,62000.00,0,[{'img': 'https://images10.gaadi.com/usedcar_image/origi...,8,False,tata indica ev2 ls,tata,tata indica ev2,ls,pune,225000.00,0,dealer,partner,"['power steering', 'remote trunk opener', 'air condition...","['power steering', 'remote trunk opener', 'remote fuel l...","['air conditioner', 'adjustable steering', 'digital odom...","['adjustable head lights', 'power adjustable exterior re...","['child safety locks', 'passenger side rear view mirror'...",white,cr4 diesel engine,4.00,4.00,dohc,True,True,3690.00,1665.00,1485.00,2400.00,NaN,NaN,1080.00,NaN,5 speed,fwd,5.00,power,4.90,ventilated disc,drum,155.00,14.50,tubeless radial,5.00,220.00,used,maharashtra,white,first,Common Rail Injection,NaN,NaN,NaN,69.00,4000.00,140.00,2400.00,NaN,NaN
37812,a96fbcd7-c183-4829-ae97-b2581afe4bac,ambegaon narhe,2018,sedan,manual,diesel,54000.00,0,[{'img': ''}],0,False,tata tigor 1.05 revotorq xz,tata,tata tigor,1.05 revotorq xz,pune,530000.00,0,dealer,partner,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'power windows...","['air conditioner', 'heater', 'adjustable steering', 'di...","['adjustable head lights', 'fog lights front', 'power ad...","['anti lock braking system', 'centeral locking', 'power ...",orange,revotorq engine,3.00,4.00,dohc,True,True,3992.00,1677.00,1537.00,2450.00,1400.00,1420.00,1120.00,NaN,5 speed,fwd,5.00,power,NaN,disc,drum,NaN,16.80,tubeless radial,4.00,419.00,used,maharashtra,orange,first,Common Rail Injection,16.00,14.00,NaN,69.00,4000.00,140.00,2400.00,75.00,NaN

In [9]:
# Random sample of 5 rows
print("\n🎲 Random Sample (5 Rows):")
df.sample(5, random_state=42)

🎲 Random Sample (5 Rows):

,usedCarSkuId,loc,myear,body,transmission,fuel,km,ip,images,imgCount,threesixty,dvn,oem,model,variant,City,listed_price,discountValue,utype,carType,top_features,comfort_features,interior_features,exterior_features,safety_features,Color,Engine Type,No of Cylinder,Valves per Cylinder,Valve Configuration,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seats,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,Doors,Cargo Volume,model_type_new,state,exterior_color,owner_type,Fuel Suppy System,Compression Ratio,Alloy Wheel Size,Ground Clearance Unladen,Max Power Delivered,Max Power At,Max Torque Delivered,Max Torque At,Bore,Stroke
3288,eb6af527-4540-47e6-bec4-289b2090ab5b,NaN,2016,muv,manual,diesel,150000.00,0,[{'img': 'https://stimg2.cardekho.com/images/usedcarimag...,10,False,toyota innova 2.5 g (diesel) 7 seater bs iv,toyota,toyota innova,2.5 g (diesel) 7 seater bs iv,nagpur,950000.00,0,individual,partner,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'power windows...","['air conditioner', 'heater', 'adjustable steering', 'di...","['adjustable head lights', 'power adjustable exterior re...","['centeral locking', 'power door locks', 'child safety l...",white,2kd-ftv diesel engine,4.00,4.00,dohc,True,True,4585.00,1760.00,1760.00,2750.00,1510.00,1510.00,1600.00,2300.00,5 speed,rwd,7.00,power,5.40,ventilated disc,drum,155.00,13.30,tubeless radial,5.00,300.00,used,maharashtra,white,second,Common Rail Injection,NaN,NaN,NaN,100.60,3600.00,200.00,2400.00,NaN,NaN
36026,18323d76-4691-43b0-82da-05dbb4076d81,new delhi g.p.o.,2014,suv,manual,diesel,53755.00,0,[{'img': 'https://images10.gaadi.com/usedcar_image/origi...,21,False,mahindra xuv500 w8 fwd,mahindra,mahindra xuv500,w8 fwd,new delhi,500000.00,0,dealer,partner,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'power windows...","['air conditioner', 'heater', 'adjustable steering', 'di...","['adjustable head lights', 'fog lights front', 'power ad...","['anti lock braking system', 'centeral locking', 'child ...",white,mhawk diesel engine,4.00,4.00,dohc,True,True,4585.00,1890.00,1785.00,2700.00,NaN,NaN,NaN,2450.00,6 speed,awd,7.00,power,5.60,caliper,caliper,175.00,12.50,tubeless radial,5.00,NaN,used,delhi,white,first,Direct Injection,NaN,17.00,NaN,140.00,3750.00,330.00,2200.00,NaN,NaN
36285,ba8eb0a1-7c3c-46fe-bee5-e82404240aab,sector 39,2020,hatchback,manual,petrol,53838.00,0,[{'img': 'https://images10.gaadi.com/usedcar_image/origi...,15,False,tata altroz xz option,tata,tata altroz,xz option,noida,738000.00,0,dealer,corporate,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'power windows...","['air conditioner', 'heater', 'adjustable steering', 'di...","['adjustable head lights', 'fog lights front', 'power ad...","['anti lock braking system', 'centeral locking', 'power ...",white,1.2 l revotron,3.00,4.00,NaN,False,False,3990.00,1755.00,1523.00,2501.00,NaN,NaN,NaN,NaN,5 speed,NaN,5.00,power,5.00,disc,drum,NaN,NaN,tubeless radial,5.00,345.00,used,uttar pradesh,white,first,NaN,NaN,16.00,NaN,84.88,6000.00,113.00,3300.00,NaN,NaN
21250,3f395a38-aecf-4585-afcc-d8e7f7251c6d,dehradun,2016,sedan,manual,petrol,34213.00,0,[{'img': 'https://images10.gaadi.com/usedcar_image/origi...,22,True,honda city i vtec v,honda,honda city,i vtec v,dehradun,660000.00,0,dealer,partner,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'power windows...","['air conditioner', 'heater', 'adjustable steering', 'di...","['adjustable head lights', 'fog lights front', 'power ad...","['anti lock braking system', 'centeral locking', 'power ...",white orchid pearl,i vtec engine,4.00,4.00,sohc,False,False,4440.00,1695.00,1495.00,2600.00,1480.00,1465.00,1049.00,NaN,5 speed,fwd,5.00,power,5.30,disc,drum,195.00,10.00,tubeless radial,4.00,510.00,used,uttarakhand,white orchid pearl,first,Common Rail Injection,10.30,15.00,NaN,117.30,6600.00,145.00,4600.00,73.00,NaN
1453,02eff4df-1c2d-4402-912a-671ea3452535,kandivali west,2017,muv,manual,diesel,63125.00,0,[{'img': 'https://images10.gaadi.com/usedcar_image/origi...,15,False,maruti ertiga shvs vdi limited edition,maruti,maruti ertiga,shvs vdi limited edition,mumbai,899999.00,0,dealer,partner,"['power steering', 'power windows front', 'air condition...","['power steering', 'power windows front', 'power windows...","['air conditioner', 'heater', 'digital odometer', 'tacho...","['adjustable head lights', 'fog lights front', 'power ad...","['anti lock braking system', 'brake assist', 'centeral l...",white,d13a shvs engine,4.00,4.00,dohc,True,True,4296.00,1695.00,1685.00,2740.00,1480.00,1490.00,1260.00,NaN,5 speed,fwd,7.00,power,5.20,ventilated disc,drum,160.00,13.30,tubeless radial,5.00,135.00,used,maharashtra,white,first,Common Rail Injection,17.60,NaN,NaN,88.50,4000.00,200.00,1750.00,69.60,NaN

---
## 2. Data Fields Understanding

In [10]:
# Compact info
print("📑 DataFrame Info:")
print()
df.info()

📑 DataFrame Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37813 entries, 0 to 37812
Data columns (total 66 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   usedCarSkuId              37813 non-null  object
 1   loc                       31963 non-null  object
 2   myear                     37813 non-null  int64
 3   body                      37794 non-null  object
 4   transmission              37813 non-null  object
 5   fuel                      37813 non-null  object
 6   km                        37813 non-null  float64
 7   ip                        37813 non-null  int64
 8   images                    37813 non-null  object
 9   imgCount                  37813 non-null  int64
 10  threesixty                37813 non-null  bool
 11  dvn                       37813 non-null  object
 12  oem                       37813 non-null  object
 13  model                     37813 non-null  object
 14  variant                   37813 non-null  object
 15  City                      37813 non-null  object
 16  listed_price              37813 non-null  float64
 17  discountValue             37813 non-null  int64
 18  utype                     37813 non-null  object
 19  carType                   37813 non-null  object
 20  top_features              37813 non-null  object
 21  comfort_features          37813 non-null  object
 22  interior_features         37813 non-null  object
 23  exterior_features         37813 non-null  object
 24  safety_features           37813 non-null  object
 25  Color                     37653 non-null  object
 26  Engine Type               36945 non-null  object
 27  No of Cylinder            37670 non-null  float64
 28  Valves per Cylinder       37585 non-null  float64
 29  Valve Configuration       29851 non-null  object
 30  Turbo Charger             37813 non-null  bool
 31  Super Charger             37813 non-null  bool
 32  Length                    37451 non-null  float64
 33  Width                     37442 non-null  float64
 34  Height                    37450 non-null  float64
 35  Wheel Base                37257 non-null  float64
 36  Front Tread               21939 non-null  float64
 37  Rear Tread                21938 non-null  float64
 38  Kerb Weight               24674 non-null  float64
 39  Gross Weight              16923 non-null  float64
 40  Gear Box                  37342 non-null  object
 41  Drive Type                33316 non-null  object
 42  Seats                     37795 non-null  float64
 43  Steering Type             37005 non-null  object
 44  Turning Radius            31965 non-null  float64
 45  Front Brake Type          37486 non-null  object
 46  Rear Brake Type           37487 non-null  object
 47  Top Speed                 22461 non-null  float64
 48  Acceleration              23825 non-null  float64
 49  Tyre Type                 37556 non-null  object
 50  Doors                     37769 non-null  float64
 51  Cargo Volume              31081 non-null  float64
 52  model_type_new            37813 non-null  object
 53  state                     37813 non-null  object
 54  exterior_color            37690 non-null  object
 55  owner_type                37813 non-null  object
 56  Fuel Suppy System         32311 non-null  object
 57  Compression Ratio         10012 non-null  float64
 58  Alloy Wheel Size          23352 non-null  float64
 59  Ground Clearance Unladen  2152 non-null   float64
 60  Max Power Delivered       37582 non-null  float64
 61  Max Power At              35566 non-null  float64
 62  Max Torque Delivered      37582 non-null  float64
 63  Max Torque At             35837 non-null  float64
 64  Bore                      12636 non-null  float64
 65  Stroke                    513 non-null    float64
dtypes: bool(3), float64(27), int64(4), object(32)
memory usage: 18.3+ MB

In [11]:
# Detailed column-level summary
field_info = pd.DataFrame({
    'Column Name': df.columns,
    'Data Type': df.dtypes.values,
    'Non-Null Count': df.notnull().sum().values,
    'Null Count': df.isnull().sum().values,
    'Unique Values': df.nunique().values,
    'Sample Value': [df[col].dropna().iloc[0] if df[col].notnull().any() else 'ALL NULL' for col in df.columns]
})
field_info.index = range(1, len(field_info) + 1)
field_info.index.name = '#'

print("\n📋 COMPLETE DATA FIELDS SUMMARY")
print("="*100)
field_info

📋 COMPLETE DATA FIELDS SUMMARY
====================================================================================================

,Column Name,Data Type,Non-Null Count,Null Count,Unique Values,Sample Value
#,,,,,,
1,usedCarSkuId,object,37813,0,37813,7111bf25-97af-47f9-867b-40879190d800
2,loc,object,31963,5850,397,gomti nagar
3,myear,int64,37813,0,34,2016
4,body,object,37794,19,11,hatchback
5,transmission,object,37813,0,2,manual
...,...,...,...,...,...,...
62,Max Power At,float64,35566,2247,50,6200.00
63,Max Torque Delivered,float64,37582,231,330,77.00
64,Max Torque At,float64,35837,1976,111,3500.00
65,Bore,float64,12636,25177,67,69.00
66,Stroke,float64,513,37300,21,85.00

In [12]:
# List all column names
print("\n📝 All Column Names:")
print("-"*40)
for i, col in enumerate(df.columns, 1):
    print(f"  {i:>2}. {col}")

📝 All Column Names:
----------------------------------------
   1. usedCarSkuId
   2. loc
   3. myear
   4. body
   5. transmission
   6. fuel
   7. km
   8. ip
   9. images
  10. imgCount
  11. threesixty
  12. dvn
  13. oem
  14. model
  15. variant
  16. City
  17. listed_price
  18. discountValue
  19. utype
  20. carType
  21. top_features
  22. comfort_features
  23. interior_features
  24. exterior_features
  25. safety_features
  26. Color
  27. Engine Type
  28. No of Cylinder
  29. Valves per Cylinder
  30. Valve Configuration
  31. Turbo Charger
  32. Super Charger
  33. Length
  34. Width
  35. Height
  36. Wheel Base
  37. Front Tread
  38. Rear Tread
  39. Kerb Weight
  40. Gross Weight
  41. Gear Box
  42. Drive Type
  43. Seats
  44. Steering Type
  45. Turning Radius
  46. Front Brake Type
  47. Rear Brake Type
  48. Top Speed
  49. Acceleration
  50. Tyre Type
  51. Doors
  52. Cargo Volume
  53. model_type_new
  54. state
  55. exterior_color
  56. owner_type
  57. Fuel Suppy System
  58. Compression Ratio
  59. Alloy Wheel Size
  60. Ground Clearance Unladen
  61. Max Power Delivered
  62. Max Power At
  63. Max Torque Delivered
  64. Max Torque At
  65. Bore
  66. Stroke

---
## 3. Missing Values Analysis

In [13]:
# Missing values count and percentage
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    'Column': missing.index,
    'Missing Count': missing.values,
    'Missing %': missing_pct.values,
    'Present Count': df.notnull().sum().values,
    'Present %': ((df.notnull().sum() / len(df)) * 100).values
})

# Sort by missing percentage (descending)
missing_df = missing_df.sort_values('Missing %', ascending=False).reset_index(drop=True)
missing_df.index = range(1, len(missing_df) + 1)
missing_df.index.name = '#'

print("🔴 MISSING VALUES ANALYSIS (sorted by missing %)")
print("="*80)
missing_df

🔴 MISSING VALUES ANALYSIS (sorted by missing %)
================================================================================

,Column,Missing Count,Missing %,Present Count,Present %
#,,,,,
1,Stroke,37300,98.64,513,1.36
2,Ground Clearance Unladen,35661,94.31,2152,5.69
3,Compression Ratio,27801,73.52,10012,26.48
4,Bore,25177,66.58,12636,33.42
5,Gross Weight,20890,55.25,16923,44.75
...,...,...,...,...,...
62,model,0,0.00,37813,100.00
63,variant,0,0.00,37813,100.00
64,owner_type,0,0.00,37813,100.00
65,model_type_new,0,0.00,37813,100.00
66,state,0,0.00,37813,100.00

In [14]:
# Summary of missing values
cols_with_missing = (missing > 0).sum()
cols_without_missing = (missing == 0).sum()
total_missing_cells = missing.sum()
total_cells = df.size

print("\n📊 MISSING VALUES SUMMARY")
print("="*50)
print(f"Columns WITH missing values    : {cols_with_missing} / {len(df.columns)}")
print(f"Columns WITHOUT missing values : {cols_without_missing} / {len(df.columns)}")
print(f"Total missing cells            : {total_missing_cells:,} / {total_cells:,}")
print(f"Overall missing percentage     : {(total_missing_cells/total_cells)*100:.2f}%")
print("="*50)

📊 MISSING VALUES SUMMARY
==================================================
Columns WITH missing values    : 38 / 66
Columns WITHOUT missing values : 28 / 66
Total missing cells            : 282,038 / 2,495,658
Overall missing percentage     : 11.30%
==================================================

In [15]:
# Columns with >50% missing (if any)
high_missing = missing_df[missing_df['Missing %'] > 50]
if len(high_missing) > 0:
    print("\n⚠️  Columns with MORE THAN 50% missing values:")
    print("-"*50)
    for _, row in high_missing.iterrows():
        print(f"  • {row['Column']} — {row['Missing %']:.2f}% missing")
else:
    print("\n✅ No column has more than 50% missing values.")

⚠️  Columns with MORE THAN 50% missing values:
--------------------------------------------------
  • Stroke — 98.64% missing
  • Ground Clearance Unladen — 94.31% missing
  • Compression Ratio — 73.52% missing
  • Bore — 66.58% missing
  • Gross Weight — 55.25% missing

---
## 4. Duplicate Data Check

In [16]:
# Check for exact duplicate rows
total_duplicates = df.duplicated().sum()

print("🔁 DUPLICATE ROWS ANALYSIS")
print("="*50)
print(f"Total rows               : {len(df):,}")
print(f"Duplicate rows           : {total_duplicates:,}")
print(f"Unique rows              : {len(df) - total_duplicates:,}")
print(f"Duplicate percentage     : {(total_duplicates/len(df))*100:.2f}%")
print("="*50)

if total_duplicates > 0:
    print(f"\n⚠️  {total_duplicates:,} duplicate rows found!")
else:
    print("\n✅ No duplicate rows found in the dataset.")

🔁 DUPLICATE ROWS ANALYSIS
==================================================
Total rows               : 37,813
Duplicate rows           : 0
Unique rows              : 37,813
Duplicate percentage     : 0.00%
==================================================

✅ No duplicate rows found in the dataset.

In [17]:
# Show sample duplicates (if any)
if total_duplicates > 0:
    print("\n🔍 Sample Duplicate Rows (first 5):")
    display(df[df.duplicated(keep=False)].head(10))
else:
    print("No duplicates to display.")

No duplicates to display.

In [18]:
# Check for duplicates based on a likely unique identifier
if 'usedCarSkuId' in df.columns:
    id_duplicates = df['usedCarSkuId'].duplicated().sum()
    print(f"\n🔑 Duplicate check on 'usedCarSkuId':")
    print(f"   Duplicate IDs : {id_duplicates:,}")
    print(f"   Unique IDs    : {df['usedCarSkuId'].nunique():,}")
    if id_duplicates > 0:
        print(f"   ⚠️  There are {id_duplicates} duplicate usedCarSkuId values!")
    else:
        print(f"   ✅ All usedCarSkuId values are unique.")

🔑 Duplicate check on 'usedCarSkuId':
   Duplicate IDs : 0
   Unique IDs    : 37,813
   ✅ All usedCarSkuId values are unique.

---
## 5. Basic Statistical Summary

In [19]:
# Statistical summary for NUMERICAL columns
print("📈 STATISTICAL SUMMARY — Numerical Columns")
print("="*80)
df.describe().T

📈 STATISTICAL SUMMARY — Numerical Columns
================================================================================

,count,mean,std,min,25%,50%,75%,max
myear,37813.00,2015.57,3.78,1983.00,2013.00,2016.00,2018.00,2023.00
km,37813.00,62409.30,58472.16,101.00,31739.00,56726.00,83310.00,6300000.00
ip,37813.00,0.01,0.10,0.00,0.00,0.00,0.00,1.00
imgCount,37813.00,15.57,8.36,0.00,10.00,15.00,21.00,74.00
listed_price,37813.00,799986.81,3043044.88,11963.00,320000.00,525000.00,855272.00,550000555.00
discountValue,37813.00,73.28,2805.78,0.00,0.00,0.00,0.00,200000.00
No of Cylinder,37670.00,3.82,0.54,1.00,4.00,4.00,4.00,16.00
Valves per Cylinder,37585.00,3.89,0.48,1.00,4.00,4.00,4.00,48.00
Length,37451.00,4113.62,399.36,2752.00,3795.00,3995.00,4440.00,5982.00
Width,37442.00,1725.59,128.29,1312.00,1680.00,1710.00,1790.00,2236.00
Height,37450.00,1577.55,115.15,1165.00,1495.00,1530.00,1642.00,2075.00
Wheel Base,37257.00,2545.82,155.30,1840.00,2425.00,2520.00,2647.00,3772.00
Front Tread,21939.00,1470.02,90.37,1143.00,1420.00,1485.00,1530.00,1705.00
Rear Tread,21938.00,1469.29,100.56,15.00,1420.00,1493.00,1525.00,1834.00
Kerb Weight,24674.00,1146.36,318.52,451.00,935.00,1066.00,1230.00,2962.00
Gross Weight,16923.00,1709.09,441.59,785.00,1350.00,1595.00,1967.50,3490.00
Seats,37795.00,5.24,0.72,0.00,5.00,5.00,5.00,14.00
Turning Radius,31965.00,5.49,49.40,3.50,4.80,5.10,5.30,6250.00
Top Speed,22461.00,172.99,26.63,70.00,156.00,168.56,189.00,340.00
Acceleration,23825.00,13.13,3.31,2.50,11.07,13.20,14.85,44.04
Doors,37769.00,4.66,0.50,2.00,4.00,5.00,5.00,6.00
Cargo Volume,31081.00,363.09,130.41,20.00,256.00,350.00,465.00,2055.00
Compression Ratio,10012.00,12.83,5.26,4.17,10.10,10.50,16.20,81.00
Alloy Wheel Size,23352.00,15.45,1.52,7.00,14.00,16.00,16.00,21.00
Ground Clearance Unladen,2152.00,179.42,25.99,91.00,178.00,190.00,192.00,213.00
Max Power Delivered,37582.00,102.75,42.78,10.80,74.96,88.50,118.35,769.31
Max Power At,35566.00,5102.92,1056.28,1620.00,4000.00,5500.00,6000.00,8250.00
Max Torque Delivered,37582.00,178.77,106.35,4.80,110.00,145.00,224.00,900.00
Max Torque At,35837.00,3161.85,1025.05,160.00,2125.00,3375.00,4000.00,21800.00
Bore,12636.00,72.41,11.91,2.85,69.60,73.00,76.50,165.00
Stroke,513.00,83.50,4.65,71.50,82.50,85.00,85.80,104.90

In [20]:
# Statistical summary for CATEGORICAL (object) columns
print("\n📝 STATISTICAL SUMMARY — Categorical Columns")
print("="*80)
df.describe(include='object').T

📝 STATISTICAL SUMMARY — Categorical Columns
================================================================================

,count,unique,top,freq
usedCarSkuId,37813,37813,a96fbcd7-c183-4829-ae97-b2581afe4bac,1
loc,31963,397,pune city,3483
body,37794,11,hatchback,15053
transmission,37813,2,manual,28894
fuel,37813,5,petrol,21773
images,37813,37135,[{'img': ''}],679
dvn,37813,4128,maruti swift vxi,347
oem,37813,46,maruti,9950
model,37813,382,honda city,1911
variant,37813,3430,vxi,1233
City,37813,617,new delhi,4969
utype,37813,2,dealer,31963
carType,37813,3,partner,32512
top_features,37813,400,"['power steering', 'power windows front', 'air condition...",6974
comfort_features,37813,2016,"['power steering', 'power windows front', 'power windows...",573
interior_features,37813,527,"['air conditioner', 'heater', 'adjustable steering', 'di...",2745
exterior_features,37813,1893,"['adjustable head lights', 'fog lights front', 'power ad...",434
safety_features,37813,2116,"['anti lock braking system', 'centeral locking', 'power ...",718
Color,37653,747,white,10059
Engine Type,36945,566,in-line engine,3370
Valve Configuration,29851,5,dohc,23571
Gear Box,37342,11,5 speed,25203
Drive Type,33316,6,fwd,27632
Steering Type,37005,2,power,36348
Front Brake Type,37486,6,disc,23334
Rear Brake Type,37487,6,drum,29973
Tyre Type,37556,4,tubeless radial,29108
model_type_new,37813,1,used,37813
state,37813,33,maharashtra,8628
exterior_color,37690,747,white,10067
owner_type,37813,6,first,26571
Fuel Suppy System,32311,14,Multi-Point Fuel Injection,14055

In [21]:
# Full describe (all columns)
print("\n📊 COMPLETE STATISTICAL SUMMARY (All Columns)")
print("="*80)
df.describe(include='all').T

📊 COMPLETE STATISTICAL SUMMARY (All Columns)
================================================================================

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
usedCarSkuId,37813,37813,a96fbcd7-c183-4829-ae97-b2581afe4bac,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loc,31963,397,pune city,3483,NaN,NaN,NaN,NaN,NaN,NaN,NaN
myear,37813.00,NaN,NaN,NaN,2015.57,3.78,1983.00,2013.00,2016.00,2018.00,2023.00
body,37794,11,hatchback,15053,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transmission,37813,2,manual,28894,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
Max Power At,35566.00,NaN,NaN,NaN,5102.92,1056.28,1620.00,4000.00,5500.00,6000.00,8250.00
Max Torque Delivered,37582.00,NaN,NaN,NaN,178.77,106.35,4.80,110.00,145.00,224.00,900.00
Max Torque At,35837.00,NaN,NaN,NaN,3161.85,1025.05,160.00,2125.00,3375.00,4000.00,21800.00
Bore,12636.00,NaN,NaN,NaN,72.41,11.91,2.85,69.60,73.00,76.50,165.00
Stroke,513.00,NaN,NaN,NaN,83.50,4.65,71.50,82.50,85.00,85.80,104.90

---
## 6. Numerical vs Categorical Columns

In [22]:
# Identify numerical and categorical columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
boolean_cols = df.select_dtypes(include=['bool']).columns.tolist()

print("📊 COLUMN TYPE CLASSIFICATION")
print("="*60)
print(f"\n🔢 Numerical Columns ({len(numerical_cols)}):")
print("-"*40)
for i, col in enumerate(numerical_cols, 1):
    print(f"  {i:>2}. {col} (dtype: {df[col].dtype})")

print(f"\n🏷️  Categorical Columns ({len(categorical_cols)}):")
print("-"*40)
for i, col in enumerate(categorical_cols, 1):
    print(f"  {i:>2}. {col} (dtype: {df[col].dtype})")

if boolean_cols:
    print(f"\n✅ Boolean Columns ({len(boolean_cols)}):")
    print("-"*40)
    for i, col in enumerate(boolean_cols, 1):
        print(f"  {i:>2}. {col} (dtype: {df[col].dtype})")

print(f"\n{'='*60}")
print(f"Total: {len(numerical_cols)} numerical + {len(categorical_cols)} categorical + {len(boolean_cols)} boolean = {len(df.columns)} columns")

📊 COLUMN TYPE CLASSIFICATION
============================================================

🔢 Numerical Columns (31):
----------------------------------------
   1. myear (dtype: int64)
   2. km (dtype: float64)
   3. ip (dtype: int64)
   4. imgCount (dtype: int64)
   5. listed_price (dtype: float64)
   6. discountValue (dtype: int64)
   7. No of Cylinder (dtype: float64)
   8. Valves per Cylinder (dtype: float64)
   9. Length (dtype: float64)
  10. Width (dtype: float64)
  11. Height (dtype: float64)
  12. Wheel Base (dtype: float64)
  13. Front Tread (dtype: float64)
  14. Rear Tread (dtype: float64)
  15. Kerb Weight (dtype: float64)
  16. Gross Weight (dtype: float64)
  17. Seats (dtype: float64)
  18. Turning Radius (dtype: float64)
  19. Top Speed (dtype: float64)
  20. Acceleration (dtype: float64)
  21. Doors (dtype: float64)
  22. Cargo Volume (dtype: float64)
  23. Compression Ratio (dtype: float64)
  24. Alloy Wheel Size (dtype: float64)
  25. Ground Clearance Unladen (dtype: float64)
  26. Max Power Delivered (dtype: float64)
  27. Max Power At (dtype: float64)
  28. Max Torque Delivered (dtype: float64)
  29. Max Torque At (dtype: float64)
  30. Bore (dtype: float64)
  31. Stroke (dtype: float64)

🏷️  Categorical Columns (32):
----------------------------------------
   1. usedCarSkuId (dtype: object)
   2. loc (dtype: object)
   3. body (dtype: object)
   4. transmission (dtype: object)
   5. fuel (dtype: object)
   6. images (dtype: object)
   7. dvn (dtype: object)
   8. oem (dtype: object)
   9. model (dtype: object)
  10. variant (dtype: object)
  11. City (dtype: object)
  12. utype (dtype: object)
  13. carType (dtype: object)
  14. top_features (dtype: object)
  15. comfort_features (dtype: object)
  16. interior_features (dtype: object)
  17. exterior_features (dtype: object)
  18. safety_features (dtype: object)
  19. Color (dtype: object)
  20. Engine Type (dtype: object)
  21. Valve Configuration (dtype: object)
  22. Gear Box (dtype: object)
  23. Drive Type (dtype: object)
  24. Steering Type (dtype: object)
  25. Front Brake Type (dtype: object)
  26. Rear Brake Type (dtype: object)
  27. Tyre Type (dtype: object)
  28. model_type_new (dtype: object)
  29. state (dtype: object)
  30. exterior_color (dtype: object)
  31. owner_type (dtype: object)
  32. Fuel Suppy System (dtype: object)

✅ Boolean Columns (3):
----------------------------------------
   1. threesixty (dtype: bool)
   2. Turbo Charger (dtype: bool)
   3. Super Charger (dtype: bool)

============================================================
Total: 31 numerical + 32 categorical + 3 boolean = 66 columns

In [23]:
# Summary table of column types
type_summary = pd.DataFrame({
    'Column Type': ['Numerical (int/float)', 'Categorical (object)', 'Boolean'],
    'Count': [len(numerical_cols), len(categorical_cols), len(boolean_cols)],
    'Columns': [
        ', '.join(numerical_cols),
        ', '.join(categorical_cols),
        ', '.join(boolean_cols) if boolean_cols else 'None'
    ]
})
type_summary.index = range(1, len(type_summary) + 1)
type_summary.index.name = '#'

print("\n📋 COLUMN TYPE SUMMARY TABLE")
type_summary

📋 COLUMN TYPE SUMMARY TABLE

,Column Type,Count,Columns
#,,,
1,Numerical (int/float),31,"myear, km, ip, imgCount, listed_price, discountValue, No..."
2,Categorical (object),32,"usedCarSkuId, loc, body, transmission, fuel, images, dvn..."
3,Boolean,3,"threesixty, Turbo Charger, Super Charger"

In [24]:
# Unique value counts for categorical columns
print("\n🏷️  UNIQUE VALUE COUNTS — Categorical Columns")
print("="*60)
cat_unique = pd.DataFrame({
    'Column': categorical_cols,
    'Unique Values': [df[col].nunique() for col in categorical_cols],
    'Most Frequent': [df[col].mode().iloc[0] if not df[col].mode().empty else 'N/A' for col in categorical_cols],
    'Frequency of Most Frequent': [df[col].value_counts().iloc[0] if not df[col].value_counts().empty else 0 for col in categorical_cols]
}).sort_values('Unique Values', ascending=False).reset_index(drop=True)
cat_unique.index = range(1, len(cat_unique) + 1)
cat_unique.index.name = '#'
cat_unique

🏷️  UNIQUE VALUE COUNTS — Categorical Columns
============================================================

,Column,Unique Values,Most Frequent,Frequency of Most Frequent
#,,,,
1,usedCarSkuId,37813,00006fea-858a-4ee2-8d29-250dfbe595dd,1
2,images,37135,[{'img': ''}],679
3,dvn,4128,maruti swift vxi,347
4,variant,3430,vxi,1233
5,safety_features,2116,"['anti lock braking system', 'centeral locking', 'power ...",718
6,comfort_features,2016,"['power steering', 'power windows front', 'power windows...",573
7,exterior_features,1893,"['adjustable head lights', 'fog lights front', 'power ad...",434
8,Color,747,white,10059
9,exterior_color,747,white,10067
10,City,617,new delhi,4969
11,Engine Type,566,in-line engine,3370
12,interior_features,527,"['air conditioner', 'heater', 'adjustable steering', 'di...",2745
13,top_features,400,"['power steering', 'power windows front', 'air condition...",6974
14,loc,397,pune city,3483
15,model,382,honda city,1911
16,oem,46,maruti,9950
17,state,33,maharashtra,8628
18,Fuel Suppy System,14,Multi-Point Fuel Injection,14055
19,body,11,hatchback,15053
20,Gear Box,11,5 speed,25203
21,Rear Brake Type,6,drum,29973
22,owner_type,6,first,26571
23,Drive Type,6,fwd,27632
24,Front Brake Type,6,disc,23334
25,Valve Configuration,5,dohc,23571
26,fuel,5,petrol,21773
27,Tyre Type,4,tubeless radial,29108
28,carType,3,partner,32512
29,utype,2,dealer,31963
30,transmission,2,manual,28894
31,Steering Type,2,power,36348
32,model_type_new,1,used,37813

In [25]:
# Value range for numerical columns
print("\n🔢 VALUE RANGE — Numerical Columns")
print("="*60)
num_range = pd.DataFrame({
    'Column': numerical_cols,
    'Min': [df[col].min() for col in numerical_cols],
    'Max': [df[col].max() for col in numerical_cols],
    'Mean': [df[col].mean() for col in numerical_cols],
    'Median': [df[col].median() for col in numerical_cols],
    'Std Dev': [df[col].std() for col in numerical_cols]
}).reset_index(drop=True)
num_range.index = range(1, len(num_range) + 1)
num_range.index.name = '#'
num_range

🔢 VALUE RANGE — Numerical Columns
============================================================

,Column,Min,Max,Mean,Median,Std Dev
#,,,,,,
1,myear,1983.00,2023.00,2015.57,2016.00,3.78
2,km,101.00,6300000.00,62409.30,56726.00,58472.16
3,ip,0.00,1.00,0.01,0.00,0.10
4,imgCount,0.00,74.00,15.57,15.00,8.36
5,listed_price,11963.00,550000555.00,799986.81,525000.00,3043044.88
6,discountValue,0.00,200000.00,73.28,0.00,2805.78
7,No of Cylinder,1.00,16.00,3.82,4.00,0.54
8,Valves per Cylinder,1.00,48.00,3.89,4.00,0.48
9,Length,2752.00,5982.00,4113.62,3995.00,399.36
10,Width,1312.00,2236.00,1725.59,1710.00,128.29
11,Height,1165.00,2075.00,1577.55,1530.00,115.15
12,Wheel Base,1840.00,3772.00,2545.82,2520.00,155.30
13,Front Tread,1143.00,1705.00,1470.02,1485.00,90.37
14,Rear Tread,15.00,1834.00,1469.29,1493.00,100.56
15,Kerb Weight,451.00,2962.00,1146.36,1066.00,318.52
16,Gross Weight,785.00,3490.00,1709.09,1595.00,441.59
17,Seats,0.00,14.00,5.24,5.00,0.72
18,Turning Radius,3.50,6250.00,5.49,5.10,49.40
19,Top Speed,70.00,340.00,172.99,168.56,26.63
20,Acceleration,2.50,44.04,13.13,13.20,3.31
21,Doors,2.00,6.00,4.66,5.00,0.50
22,Cargo Volume,20.00,2055.00,363.09,350.00,130.41
23,Compression Ratio,4.17,81.00,12.83,10.50,5.26
24,Alloy Wheel Size,7.00,21.00,15.45,16.00,1.52
25,Ground Clearance Unladen,91.00,213.00,179.42,190.00,25.99
26,Max Power Delivered,10.80,769.31,102.75,88.50,42.78
27,Max Power At,1620.00,8250.00,5102.92,5500.00,1056.28
28,Max Torque Delivered,4.80,900.00,178.77,145.00,106.35
29,Max Torque At,160.00,21800.00,3161.85,3375.00,1025.05
30,Bore,2.85,165.00,72.41,73.00,11.91
31,Stroke,71.50,104.90,83.50,85.00,4.65

---
## 📌 Key Observations

_Run all the cells above and then fill in your key findings below:_

1. **Dataset Size:** _[rows] × [columns]_
2. **Target Variable:** `listed_price` — the price at which the used car is listed
3. **Missing Values:** _[summary of columns with highest missing %]_
4. **Duplicates:** _[number of duplicate rows found]_
5. **Data Types:** _[X numerical, Y categorical, Z boolean]_
6. **Notable Columns:** Feature columns like `top_features`, `comfort_features`, etc. appear to contain list-like strings that may need parsing

---
*End of Data Understanding Notebook*