# 📦 Retail Store Inventory Forecasting — Data Understanding

**Objective:** Understand the structure and basic properties of `retail_store_inventory.csv` before building a regression model for inventory forecasting.

This notebook covers:
1. Loading the Dataset
2. Shape & Structure
3. Data Types
4. Feature Descriptions
5. Statistical Summary
6. Missing Values
7. Duplicate Records
8. Unique Value Counts
9. Key Observations

---
## 1. Import Libraries & Load Data

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('retail_store_inventory.csv')
print('Dataset loaded successfully.')

Dataset loaded successfully.

---
## 2. Shape & First/Last Records

In [2]:
print(f'Rows   : {df.shape[0]:,}')
print(f'Columns: {df.shape[1]}')
print(f'\nColumn Names: {list(df.columns)}')

Rows   : 73,100
Columns: 15

Column Names: ['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast', 'Price', 'Discount', 'Weather Condition', 'Holiday/Promotion', 'Competitor Pricing', 'Seasonality']

In [3]:
print('--- First 5 Rows ---')
df.head()

--- First 5 Rows ---

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [4]:
print('--- Last 5 Rows ---')
df.tail()

--- Last 5 Rows ---

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
73095,2024-01-01,S005,P0016,Furniture,East,96,8,127,18.46,73.73,20,Snowy,0,72.45,Winter
73096,2024-01-01,S005,P0017,Toys,North,313,51,101,48.43,82.57,10,Cloudy,0,83.78,Autumn
73097,2024-01-01,S005,P0018,Clothing,West,278,36,151,39.65,11.11,10,Rainy,0,10.91,Winter
73098,2024-01-01,S005,P0019,Toys,East,374,264,21,270.52,53.14,20,Rainy,0,55.80,Spring
73099,2024-01-01,S005,P0020,Groceries,East,117,6,165,2.33,78.39,20,Rainy,1,79.52,Spring

In [5]:
print('--- Random Sample (5 Rows) ---')
df.sample(5, random_state=42)

--- Random Sample (5 Rows) ---

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
66127,2023-10-24,S002,P0008,Electronics,North,225,138,144,139.31,40.47,0,Snowy,1,41.97,Winter
43485,2023-03-11,S005,P0006,Toys,North,200,105,119,117.55,18.65,15,Cloudy,1,16.65,Spring
34304,2022-12-10,S001,P0005,Clothing,East,145,70,137,78.51,20.33,15,Snowy,0,18.04,Winter
34317,2022-12-10,S001,P0018,Electronics,West,350,105,157,103.11,98.65,15,Sunny,0,95.43,Spring
38631,2023-01-22,S002,P0012,Groceries,North,145,76,145,92.47,10.04,20,Sunny,0,13.01,Winter

---
## 3. Data Types & Info

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  object
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Category            73100 non-null  object
 4   Region              73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  object
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  object
dtypes: float64(3), int64(5), object(7)
memory usage: 8.4+ MB

In [7]:
print('Data Types:\n')
print(df.dtypes)
print(f'\nMemory Usage: {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB')

Data Types:

Date                   object
Store ID               object
Product ID             object
Category               object
Region                 object
Inventory Level         int64
Units Sold              int64
Units Ordered           int64
Demand Forecast       float64
Price                 float64
Discount                int64
Weather Condition      object
Holiday/Promotion       int64
Competitor Pricing    float64
Seasonality            object
dtype: object

Memory Usage: 31.37 MB

In [8]:
numerical_cols = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

print(f'Numerical Features  ({len(numerical_cols)}): {numerical_cols}')
print(f'Categorical Features({len(categorical_cols)}): {categorical_cols}')

Numerical Features  (8): ['Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast', 'Price', 'Discount', 'Holiday/Promotion', 'Competitor Pricing']
Categorical Features(7): ['Date', 'Store ID', 'Product ID', 'Category', 'Region', 'Weather Condition', 'Seasonality']

---
## 4. Feature Descriptions

In [10]:
feature_info = {
    'Date': 'Date of the inventory record',
    'Store ID': 'Unique identifier for each store',
    'Product ID': 'Unique identifier for each product',
    'Category': 'Product category (e.g., Groceries, Toys)',
    'Region': 'Geographic region of the store',
    'Inventory Level': 'Current stock count — TARGET variable',
    'Units Sold': 'Number of units sold',
    'Units Ordered': 'Number of units ordered/restocked',
    'Demand Forecast': 'Predicted demand for the product',
    'Price': 'Selling price of the product',
    'Discount': 'Discount percentage applied',
    'Weather Condition': 'Weather during the period (Rainy, Sunny, etc.)',
    'Holiday/Promotion': 'Binary flag — 1 if holiday/promotion, 0 otherwise',
    'Competitor Pricing': 'Competitor price for similar product',
    'Seasonality': 'Season of the year (Summer, Winter, etc.)'
}

pd.DataFrame({
    'Feature': feature_info.keys(),
    'Description': feature_info.values(),
    'Dtype': [str(df[col].dtype) for col in feature_info.keys()],
    'Sample Value': [df[col].iloc[0] for col in feature_info.keys()]
})

,Feature,Description,Dtype,Sample Value
0,Date,Date of the inventory record,object,2022-01-01
1,Store ID,Unique identifier for each store,object,S001
2,Product ID,Unique identifier for each product,object,P0001
3,Category,"Product category (e.g., Groceries, Toys)",object,Groceries
4,Region,Geographic region of the store,object,North
5,Inventory Level,Current stock count — TARGET variable,int64,231
6,Units Sold,Number of units sold,int64,127
7,Units Ordered,Number of units ordered/restocked,int64,55
8,Demand Forecast,Predicted demand for the product,float64,135.47
9,Price,Selling price of the product,float64,33.5
10,Discount,Discount percentage applied,int64,20
11,Weather Condition,"Weather during the period (Rainy, Sunny, etc.)",object,Rainy
12,Holiday/Promotion,"Binary flag — 1 if holiday/promotion, 0 otherwise",int64,0
13,Competitor Pricing,Competitor price for similar product,float64,29.69
14,Seasonality,"Season of the year (Summer, Winter, etc.)",object,Autumn

---
## 5. Statistical Summary

In [11]:
print('--- Numerical Features ---')
df.describe().T

--- Numerical Features ---

,count,mean,std,min,25%,50%,75%,max
Inventory Level,73100.0,274.469877,129.949514,50.00,162.00,273.000,387.0000,500.00
Units Sold,73100.0,136.464870,108.919406,0.00,49.00,107.000,203.0000,499.00
Units Ordered,73100.0,110.004473,52.277448,20.00,65.00,110.000,155.0000,200.00
Demand Forecast,73100.0,141.494720,109.254076,-9.99,53.67,113.015,208.0525,518.55
Price,73100.0,55.135108,26.021945,10.00,32.65,55.050,77.8600,100.00
Discount,73100.0,10.009508,7.083746,0.00,5.00,10.000,15.0000,20.00
Holiday/Promotion,73100.0,0.497305,0.499996,0.00,0.00,0.000,1.0000,1.00
Competitor Pricing,73100.0,55.146077,26.191408,5.03,32.68,55.010,77.8200,104.94

In [12]:
print('--- Categorical Features ---')
df.describe(include='object').T

--- Categorical Features ---

                   count unique         top   freq
Date               73100    731  2024-01-01    100
Store ID           73100      5        S001  14620
Product ID         73100     20       P0001   3655
Category           73100      5   Furniture  14699
Region             73100      4        East  18349
Weather Condition  73100      4       Sunny  18290
Seasonality        73100      4      Spring  18317

---
## 6. Missing Values

In [13]:
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)

missing_df = pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct})
print(missing_df)

print(f'\nTotal missing values: {missing.sum()}')

                    Missing Count  Missing %
Date                            0        0.0
Store ID                        0        0.0
Product ID                      0        0.0
Category                        0        0.0
Region                          0        0.0
Inventory Level                 0        0.0
Units Sold                      0        0.0
Units Ordered                   0        0.0
Demand Forecast                 0        0.0
Price                           0        0.0
Discount                        0        0.0
Weather Condition               0        0.0
Holiday/Promotion               0        0.0
Competitor Pricing              0        0.0
Seasonality                     0        0.0

Total missing values: 0

---
## 7. Duplicate Records

In [14]:
dup_count = df.duplicated().sum()
print(f'Duplicate rows: {dup_count}')

if dup_count > 0:
    print(f'Percentage: {dup_count / len(df) * 100:.2f}%')
    print('\nSample duplicates:')
    display(df[df.duplicated(keep=False)].head(10))

Duplicate rows: 0

---
## 8. Unique Value Counts

In [15]:
print('Unique values per column:\n')
for col in df.columns:
    print(f'  {col:25s} → {df[col].nunique():,} unique values')

Unique values per column:

  Date                      → 731 unique values
  Store ID                  → 5 unique values
  Product ID                → 20 unique values
  Category                  → 5 unique values
  Region                    → 4 unique values
  Inventory Level           → 451 unique values
  Units Sold                → 498 unique values
  Units Ordered             → 181 unique values
  Demand Forecast           → 31,608 unique values
  Price                     → 8,999 unique values
  Discount                  → 5 unique values
  Weather Condition         → 4 unique values
  Holiday/Promotion         → 2 unique values
  Competitor Pricing        → 9,751 unique values
  Seasonality               → 4 unique values

In [16]:
print('--- Value Counts for Categorical Columns ---\n')
for col in categorical_cols:
    if df[col].nunique() <= 20:  # Only show for low-cardinality columns
        print(f'{col}:')
        print(df[col].value_counts())
        print()

--- Value Counts for Categorical Columns ---

Store ID:
Store ID
S001    14620
S002    14620
S003    14620
S004    14620
S005    14620
Name: count, dtype: int64

Product ID:
Product ID
P0001    3655
P0002    3655
P0003    3655
P0004    3655
P0005    3655
P0006    3655
P0007    3655
P0008    3655
P0009    3655
P0010    3655
P0011    3655
P0012    3655
P0013    3655
P0014    3655
P0015    3655
P0016    3655
P0017    3655
P0018    3655
P0019    3655
P0020    3655
Name: count, dtype: int64

Category:
Category
Furniture      14699
Toys           14643
Clothing       14626
Groceries      14611
Electronics    14521
Name: count, dtype: int64

Region:
Region
East     18349
South    18297
North    18228
West     18226
Name: count, dtype: int64

Weather Condition:
Weather Condition
Sunny     18290
Rainy     18278
Snowy     18272
Cloudy    18260
Name: count, dtype: int64

Seasonality:
Seasonality
Spring    18317
Summer    18305
Winter    18285
Autumn    18193
Name: count, dtype: int64

---
## 9. Key Observations

| Aspect | Finding |
|--------|--------|
| **Rows × Columns** | ~73K rows, 15 features |
| **Target Variable** | `Inventory Level` (continuous — regression task) |
| **Numerical Features** | Units Sold, Units Ordered, Demand Forecast, Price, Discount, Competitor Pricing, Holiday/Promotion |
| **Categorical Features** | Category, Region, Weather Condition, Seasonality, Store ID, Product ID |
| **Temporal Feature** | Date |
| **Missing Values** | Check output of Section 6 above |
| **Duplicates** | Check output of Section 7 above |

### Next Steps
- Proceed to **EDA (Exploratory Data Analysis)** for deeper visual insights
- Then **Data Preprocessing** → **Feature Engineering** → **Model Building**